<?xml version="1.0"?>
<package format="2">
  <name>amr_gazebo</name>
  <version>0.1.0</version>
  <description>Örnek AMR: Gazebo simülasyonu (dünya + robot)</description>
  <maintainer email="kullanici@example.com">Kullanici</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>amr_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
</package>
